export const links = [
  {
    title: "about me",
    href: "/about-me",
    color: "#6b60ad",
    image: "/daisy.png",
    width: 30,
    height: 30,
    position: "left-1/2 top-[9%]",
  },
  {
    title: "contact",
    href: "/contact",
    color: "#9b9697",
    image: "/phone.gif",
    width: 40,
    height: 40,
    position: "left-[18%] top-[23%]",
  },
  {
    title: "work",
    href: "/work",
    color: "#9b9b6d",
    image: "/computer-1.png",
    width: 40,
    height: 40,
    position: "left-[82%] top-[23%]",
  },
  {
    title: "bookshelf",
    href: "/books",
    color: "#bc742c",
    image: "/books.gif",
    width: 25,
    height: 25,
    position: "left-[7%] top-[55%]",
  },
  {
    title: "misc",
    href: "/miscellaneous",
    color: "#fea841",
    image: "/starfish.gif",
    width: 50,
    height: 50,
    position: "left-[93%] top-[55%]",
  },
  {
    title: "cats",
    href: "/cats",
    color: "#39749c",
    image: "/kickingback.gif",
    width: 50,
    height: 50,
    position: "left-[25%] top-[88%]",
  },
  {
    title: "leave a note",
    href: "/leave-a-note",
    color: "#9b372f",
    image: "/mail.gif",
    width: 25,
    height: 25,
    position: "left-[75%] top-[88%]",
  },
];

export const POPUP_STORAGE_KEY = "mobile-menu-popup-closed";
