export const catPhotos = [
  { src: "/zecanico.jpeg" },
  { src: "/nico.jpeg" },
  { src: "/zeca.jpeg" },
  { src: "/zecanico1.jpeg" },
  { src: "/nico1.jpeg" },
  { src: "/zeca2.jpeg" },
  { src: "/nico2.jpeg" },
  { src: "/zeca3.jpeg" },
  { src: "/zecanico2.jpeg" },
  { src: "/nico3.jpeg" },
  { src: "/zeca4.jpeg" },
  { src: "/nico4.jpg" },
  { src: "/zeca5.jpeg" },
  { src: "/zecanico4.jpeg" },
  { src: "/nico5.jpeg" },
  { src: "/zeca6.jpeg" },
  { src: "/nico6.jpeg" },
  { src: "/zeca7.jpeg" },
  { src: "/zecanico5.jpeg" },
  { src: "/nico7.jpeg" },
  { src: "/zeca8.jpeg" },
  { src: "/zecanico6.jpeg" },
  { src: "/nico8.jpeg" },
  { src: "/nico9.jpg" },
  { src: "/zecanico.jpeg" },
  { src: "/gato.jpeg" },
  { src: "/gato2.jpeg" },
  { src: "/gato3.jpeg" },
  { src: "/gato4.jpeg" },
  { src: "/gato5.jpeg" },
  { src: "/gato6.jpeg" },
  { src: "/gato7.jpeg" },
  { src: "/nico-11.jpg" },
];

export const INITIAL_REPEAT_COUNT = 1;
export const REPEATS_PER_LOAD = 1;
